/** Central route paths for links and redirects. Extend as pages are added. */
export const routes = {
  home: "/",
  homeV2: "/home-v2",
  marketing: {
    about: "/about",
    features: "/features",
    integrations: "/integrations",
    pricing: "/pricing",
    blog: "/blog",
    contact: "/contact",
    faq: "/faq",
    terms: "/terms",
    privacy: "/privacy",
  },
  auth: {
    signIn: "/sign-in",
    signUp: "/sign-up",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyEmail: "/verify-email",
    twoFactor: "/2fa",
    comingSoon: "/coming-soon",
  },
  dashboard: {
    root: "/dashboard",
    analytics: "/dashboard/analytics",
    projects: "/dashboard/projects",
    aiAssistant: "/dashboard/ai-assistant",
    workflow: "/dashboard/workflow-automation",
    workflowBuilder: "/dashboard/workflow/builder",
    prompts: "/dashboard/prompts",
    integrations: "/dashboard/integrations",
    files: "/dashboard/files",
    reports: "/dashboard/reports",
    team: "/dashboard/team",
    notifications: "/dashboard/notifications",
    billing: "/dashboard/billing",
    billingInvoices: "/dashboard/billing/invoices",
    apiKeys: "/dashboard/api-keys",
    settingsProfile: "/dashboard/settings/profile",
    settingsSecurity: "/dashboard/settings/security",
    settingsAppearance: "/dashboard/settings/appearance",
    settingsNotifications: "/dashboard/settings/notifications",
  },
} as const;
